config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pet = Pet.new
    @pets = Pet.all
  end

  def create
    @pet = Pet.create(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      render :index
    end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update_attributes!(pet_params)

    redirect_to pets_path
  end

  def destroy
    @pet = Pet.find(params[:id]).delete

    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:pet_name, :owner)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudPets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/edit.html.erb
<%= form_for @pet do |f| %>
<p>
  <%= f.label :pet_name %>
  <%= f.text_field :pet_name %>
</p>
  <p>
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </p>
  <p>
    <%= f.submit 'Update pet' %>
  </p>
<% end %>

app/views/pets/index.html.erb
<%= form_for @pet do |f| %>
<p>
  <%= f.label :pet_name %>
  <%= f.text_field :pet_name %>
</p>
  <p>
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </p>
  <p>
    <%= f.submit 'Add pet' %>
  </p>
<% end %>

<% @pets.each do |pet| %>
<ul>
  <li>
    <%= pet.pet_name %>, <%= pet.owner %>
  </li>
</ul>
<% end %>

app/views/pets/show.html.erb
<ul>
  <li>
    <%= @pet.pet_name %> <%= @pet.owner %>
  </li>
</ul>

<%= link_to 'Edit pet', edit_pet_path %> |
<%= link_to 'Delete pet', pet_path(@pet), method: :delete %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Add a pet', pets_path %>